---
title: "Motor Trend Cars Shiny App (MPG)"
subtitle: "MTCars ShinyApp"
author: "Patrick Guzman (ghutty)"
framework   : html5slides        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
ext_widgets: {rCharts: [libraries/nvd3]}
mode        : selfcontained # {standalone, draft}
output: ioslides_presentation
---
## MTCars ShinyApp MPG
Manual transmissions are more fuel efficient than Automatics.  
The MTCars Shiny App provides interactive plotting of MPG by the following variables:

  - Transmission Type
  - Carborators
  - Cylinders
  - Gears

## Plot Result with Transmission Type
```{r,echo=FALSE}
mtcarsdata <- mtcars
mtcarsdata$cyl <- factor(mtcarsdata$cyl)
mtcarsdata$am <- factor(ifelse(mtcarsdata$am == 0, "Automatic", "Manual"))
mtcarsdata$vs <- factor(mtcarsdata$vs)
mtcarsdata$gear <- factor(mtcarsdata$gear)
mtcarsdata$carb <- factor(mtcarsdata$carb)
```
```{r}
boxplot(mpg~am, data = mtcarsdata, notch=FALSE, xlab = "Transmission", 
ylab = "MPG",main = "MPG (Miles Per Gallon)", varwidth = TRUE, 
col = c("orange","blue","red","green","yellow","purple"))
```

## Plot Result with Variable Cylinders

```{r}
boxplot(mpg~cyl, data = mtcarsdata, notch=FALSE, xlab = "Transmission", 
ylab = "MPG",main = "MPG (Miles Per Gallon)", varwidth = TRUE, 
col = c("orange","blue","red","green","yellow","purple"))
```

## Plot Result with Variable Gears

```{r}
boxplot(mpg~gear, data = mtcarsdata, notch=FALSE, xlab = "Transmission", 
ylab = "MPG",main = "MPG (Miles Per Gallon)", varwidth = TRUE, 
col = c("orange","blue","red","green","yellow","purple"))
```

